# Generated by Django 5.1.7 on 2025-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('question_text', models.TextField(verbose_name='Текст вопроса (Описание ситуации)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('прочитан', 'Прочитан'), ('отвечен', 'Отвечен')], default='новый', max_length=50, verbose_name='Статус')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ специалиста')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время ответа')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Юридическое лицо')], max_length=50, verbose_name='Тип клиента')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('question_topic', models.CharField(max_length=255, verbose_name='Тема вопроса')),
                ('position_juridical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность (юр. лица)')),
                ('company_name_juridical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании (юр. лица)')),
                ('inn_juridical', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН (юр. лица)')),
                ('preferred_communication', models.CharField(max_length=255, verbose_name='Предпочитаемый способ связи')),
                ('additional_files', models.FileField(blank=True, null=True, upload_to='question_files/', verbose_name='Дополнительные файлы')),
                ('consent_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
            ],
            options={
                'verbose_name': 'Вопрос клиента',
                'verbose_name_plural': 'Вопросы клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
