# Generated by Django 5.1.7 on 2025-04-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('прочитан', 'Прочитан'), ('отвечен', 'Отвечен')], default='новый', max_length=50, verbose_name='Статус')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ специалиста')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время ответа')),
            ],
            options={
                'verbose_name': 'Вопрос клиента',
                'verbose_name_plural': 'Вопросы клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
