# Generated by Django 5.1.7 on 2025-05-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestion',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Юридическое лицо')], default='individual', max_length=50, verbose_name='Тип клиента'),
        ),
    ]
