# Generated by Django 5.1.7 on 2025-04-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialist_photos/', verbose_name='Фотография специалиста')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('education', models.TextField(verbose_name='Места обучения')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Ссылки на соцсети')),
                ('entrepreneur_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Информация об ИП')),
                ('requisites', models.TextField(blank=True, null=True, verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Информация о специалисте',
                'verbose_name_plural': 'Информация о специалистах',
            },
        ),
    ]
