# Generated by Django 5.1.7 on 2025-05-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistinfo',
            options={'verbose_name': 'Информация о специалисте'},
        ),
    ]
