# Generated by Django 5.1.7 on 2025-10-01 17:36

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_specialistinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(upload_to=main.models.image_upload_path, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='specialistinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='entrepreneur_info',
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='specialistinfo',
            name='social_links',
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='content',
            field=models.TextField(default='', verbose_name='Содержимое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
