# Generated by Django 5.1.7 on 2025-10-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imageasset_alter_specialistinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistinfo',
            options={'ordering': ['created_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
