# Generated by Django 5.1.7 on 2025-06-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('request_text', models.TextField(verbose_name='Текст заявки')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Юридическое лицо')], max_length=50, verbose_name='Тип клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('status', models.CharField(choices=[('новая', 'Новая'), ('в работе', 'В работе'), ('обработана', 'Обработана'), ('отклонена', 'Отклонена')], default='новая', max_length=50, verbose_name='Статус')),
                ('position_juridical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность (юр. лица)')),
                ('company_name_juridical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании (юр. лица)')),
                ('inn_juridical', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН (юр. лица)')),
                ('preferred_communication', models.CharField(max_length=255, verbose_name='Предпочитаемый способ связи')),
                ('position_individual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность (физ. лица)')),
                ('desired_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Желаемые дата и время консультации')),
                ('additional_files', models.FileField(blank=True, null=True, upload_to='request_files/', verbose_name='Дополнительные файлы')),
                ('consent_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('selected_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Выбранная услуга')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
