# Generated by Django 5.1.7 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_answer_options_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['attempt_id', 'question_id', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_ids',
            field=models.JSONField(blank=True, default=list, help_text='Список ID выбранных вариантов для множественного выбора'),
        ),
    ]
