# Generated by Django 5.1.7 on 2025-11-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_answer_options_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['attempt_id', 'question_id', 'option_single_id']},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question', 'option_single')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_ids',
        ),
    ]
