# Generated by Django 5.1.7 on 2025-11-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_answer_option_ids'),
        ('tests', '0005_answer_option_ids'),
    ]

    operations = [
    ]
