# Generated by Django 5.1.7 on 2025-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Юридическое лицо')], max_length=50, verbose_name='Тип клиента')),
                ('category', models.CharField(choices=[('staff', 'Оценка и подбор персонала'), ('career', 'Карьерное консультирование'), ('consulting', 'Консультирование'), ('other', 'Другие услуги')], max_length=50, verbose_name='Категория услуги')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['client_type', 'category', 'name'],
            },
        ),
    ]
