# Generated by Django 5.1.7 on 2025-06-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('staff', 'Оценка и подбор персонала'), ('other', 'Другие услуги'), ('consulting', 'Консультирование'), ('career', 'Карьерное консультирование')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
