# Generated by Django 5.1.7 on 2025-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('other', 'Другие услуги'), ('career', 'Карьерное консультирование'), ('consulting', 'Консультирование'), ('staff', 'Оценка и подбор персонала')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
