# Generated by Django 5.1.7 on 2025-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('staff', 'Оценка и подбор персонала'), ('consulting', 'Консультирование'), ('career', 'Карьерное консультирование'), ('other', 'Другие услуги')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
