# Generated by Django 5.1.7 on 2025-10-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('career', 'Карьерное консультирование'), ('other', 'Другие услуги'), ('consulting', 'Консультирование'), ('staff', 'Оценка и подбор персонала')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
