# Generated by Django 5.1.7 on 2025-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('other', 'Другие услуги'), ('career', 'Карьерное консультирование'), ('staff', 'Оценка и подбор персонала'), ('consulting', 'Консультирование')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
