# Generated by Django 5.1.7 on 2025-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consulting', 'Консультирование'), ('staff', 'Оценка и подбор персонала'), ('other', 'Другие услуги'), ('career', 'Карьерное консультирование')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
