# Generated by Django 5.1.7 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('career', 'Карьерное консультирование'), ('staff', 'Оценка и подбор персонала'), ('consulting', 'Консультирование'), ('other', 'Другие услуги')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
