# Generated by Django 5.1.7 on 2025-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('staff', 'Оценка и подбор персонала'), ('career', 'Карьерное консультирование'), ('other', 'Другие услуги'), ('consulting', 'Консультирование')], max_length=50, verbose_name='Категория услуги'),
        ),
    ]
