# Generated by Django 5.1.7 on 2025-10-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created_at'], 'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
    ]
