# Generated by Django 5.1.7 on 2025-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', 'Статья'), ('bookshelf', 'Книжная полка')], default='article', max_length=20, verbose_name='Тип материала')),
                ('category', models.CharField(blank=True, choices=[('finance', 'Управление финансами'), ('time', 'Тайм менеджмент'), ('self', 'Самодиагностика и управление состоянием')], max_length=50, null=True, verbose_name='Категория (для книжной полки)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-published_date'],
            },
        ),
    ]
