# Generated by Django 5.1.7 on 2025-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('finance', 'Управление финансами'), ('time', 'Тайм менеджмент'), ('self', 'Самодиагностика и управление состоянием')], max_length=50, null=True, verbose_name='Категория (для книжной полки)'),
        ),
    ]
